groups:
  - name: container_alerts
    rules:
      - alert: MongoContainerDown
        expr: absent(container_last_seen{name="mongodb_new"}) or time() - container_last_seen{name="mongodb_new"} > 60
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Container MongoDB đã dừng"
          description: "Container 'mongodb_new' trên 103.97.125.64 không phản hồi hơn 2 phút"
