groups:
  - name: node_alerts
    rules:
      - alert: NodeExporterDown
        expr: up{job=~"node-exporter.*"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Mất kết nối tới {{ $labels.instance }}"
          description: "Node exporter trên {{ $labels.instance }} không phản hồi hơn 2 phút"
